// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     purchase.avsc
 */
package avro

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/actgardner/gogen-avro/v7/vm"
	"github.com/actgardner/gogen-avro/v7/vm/types"
)

type DescriptionUnionTypeEnum int

const (
	DescriptionUnionTypeEnumString DescriptionUnionTypeEnum = 1
)

type DescriptionUnion struct {
	Null      *types.NullVal
	String    string
	UnionType DescriptionUnionTypeEnum
}

func writeDescriptionUnion(r *DescriptionUnion, w io.Writer) error {

	if r == nil {
		err := vm.WriteLong(0, w)
		return err
	}

	err := vm.WriteLong(int64(r.UnionType), w)
	if err != nil {
		return err
	}
	switch r.UnionType {
	case DescriptionUnionTypeEnumString:
		return vm.WriteString(r.String, w)
	}
	return fmt.Errorf("invalid value for *DescriptionUnion")
}

func NewDescriptionUnion() *DescriptionUnion {
	return &DescriptionUnion{}
}

func (_ *DescriptionUnion) SetBoolean(v bool)   { panic("Unsupported operation") }
func (_ *DescriptionUnion) SetInt(v int32)      { panic("Unsupported operation") }
func (_ *DescriptionUnion) SetFloat(v float32)  { panic("Unsupported operation") }
func (_ *DescriptionUnion) SetDouble(v float64) { panic("Unsupported operation") }
func (_ *DescriptionUnion) SetBytes(v []byte)   { panic("Unsupported operation") }
func (_ *DescriptionUnion) SetString(v string)  { panic("Unsupported operation") }
func (r *DescriptionUnion) SetLong(v int64) {
	r.UnionType = (DescriptionUnionTypeEnum)(v)
}
func (r *DescriptionUnion) Get(i int) types.Field {
	switch i {
	case 0:
		return r.Null
	case 1:
		return &types.String{Target: (&r.String)}
	}
	panic("Unknown field index")
}
func (_ *DescriptionUnion) NullField(i int)                  { panic("Unsupported operation") }
func (_ *DescriptionUnion) SetDefault(i int)                 { panic("Unsupported operation") }
func (_ *DescriptionUnion) AppendMap(key string) types.Field { panic("Unsupported operation") }
func (_ *DescriptionUnion) AppendArray() types.Field         { panic("Unsupported operation") }
func (_ *DescriptionUnion) Finalize()                        {}

func (r *DescriptionUnion) MarshalJSON() ([]byte, error) {
	if r == nil {
		return []byte("null"), nil
	}
	switch r.UnionType {
	case DescriptionUnionTypeEnumString:
		return json.Marshal(map[string]interface{}{"string": r.String})
	}
	return nil, fmt.Errorf("invalid value for *DescriptionUnion")
}

func (r *DescriptionUnion) UnmarshalJSON(data []byte) error {
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(data, &fields); err != nil {
		return err
	}
	if value, ok := fields["string"]; ok {
		r.UnionType = 1
		return json.Unmarshal([]byte(value), &r.String)
	}
	return fmt.Errorf("invalid value for *DescriptionUnion")
}
