// Code generated by github.com/actgardner/gogen-avro/v7. DO NOT EDIT.
/*
 * SOURCE:
 *     purchase.avsc
 */
package avro

import (
	"io"

	"github.com/actgardner/gogen-avro/v7/compiler"
	"github.com/actgardner/gogen-avro/v7/container"
	"github.com/actgardner/gogen-avro/v7/vm"
)

func NewPurchaseWriter(writer io.Writer, codec container.Codec, recordsPerBlock int64) (*container.Writer, error) {
	str := NewPurchase()
	return container.NewWriter(writer, codec, recordsPerBlock, str.Schema())
}

// container reader
type PurchaseReader struct {
	r io.Reader
	p *vm.Program
}

func NewPurchaseReader(r io.Reader) (*PurchaseReader, error) {
	containerReader, err := container.NewReader(r)
	if err != nil {
		return nil, err
	}

	t := NewPurchase()
	deser, err := compiler.CompileSchemaBytes([]byte(containerReader.AvroContainerSchema()), []byte(t.Schema()))
	if err != nil {
		return nil, err
	}

	return &PurchaseReader{
		r: containerReader,
		p: deser,
	}, nil
}

func (r PurchaseReader) Read() (*Purchase, error) {
	t := NewPurchase()
	err := vm.Eval(r.r, r.p, t)
	return t, err
}
